### ISSUE TITLE
Rule: skipped tests in shared schemes

### ISSUE THREAD

**Issue by mattmassicotte** [mattmassicotte/XCLint#10]
I *think* understand the idea here, but this isn't an area I'm terrible familiar with. From @danielpunkass

**Comment by danielpunkass** [comment]
To clarify: this covers the scenario where you are testing a subset of tests by using the scheme editor's Test -> Info tab:

<img width="438" alt="image" src="https://github.com/mattmassicotte/XCLint/assets/14606/c36f2e30-3c78-4a50-beeb-bb3850af6085">

The problem is it's too easy to accidentally check this in. Now your shared scheme has permanently disabled tests that won't run on CI, on other devs' Macs, etc.

**Comment by danielpunkass** [comment]
The unchecked boxes correlate with a `SkippedTests` node in the .xcscheme file:

<img width="565" alt="image" src="https://github.com/mattmassicotte/XCLint/assets/14606/031644b0-be0f-44e2-818b-22ef560e34c8">

Scanning for the presence of that node in any shared schemes would be sufficient for this rule.

**Comment by mattmassicotte** [comment]
Thank you so much for the explanation. This makes sense, and I think this'll be great!

**Comment by mattmassicotte** [comment]
Addressed with 90e461ca798f7600134646d7501a46d4bb5a10a4
